#!/usr/bin/env python

import daemon
import time

print "Here!"


from doorlib import start_listening_uds



def do_main_program():
    start_listening_uds()
    time.sleep(5)
    

with daemon.DaemonContext():
    do_main_program()
