#!/usr/bin/env python

import daemon
import time

print "Here!"

import doorlib


doorlib.read_config()

doorlib.start_listening_uds()



#def do_main_program():
#    start_listening_uds()
#    time.sleep(5)
    

#with daemon.DaemonContext():
#    do_main_program()
