#!/usr/bin/env python


import doorlib
from doorlib import knock_uds
doorlib.read_config()

import argparse

parser = argparse.ArgumentParser()
parser.add_argument('credential',default='12345678')
args = parser.parse_args()

print "Knocking with credential '{0}'".format(args.credential)

knock_uds(args.credential)

