#!/usr/bin/env python3

from googleapi.memberlist import get_memberlist
from rdoorlib import GHCard,GHACL,GHMUX

def get_sheets_acl():
    values = get_memberlist()

    if not values:
        raise(Exception('No data found.'))
    else:
        new_acl = GHACL()
        # Dec is the decimal equivalent of FC+CC
        # With Google Sheets, if a cell is empty, no data is returned for that column
        # So the row object may contain between 1 and 5 columns, we'll have to deal with None's.
        # order on sheet is 'Name, Status, Card FC, Card CC, Card Dec:'
        for row in values:
            is_active = False
            fc = 0
            cc = 0
            dec = 0
            length = len(row)
            if length < 1:
                print("Bogus row, no data") # should log XXX
                continue
            name = row[0]
            if length < 2:
                print("No status data for '{}'".format(name)) # should log XXX
                continue
            if row[1] == 'ACTIVE':
                is_active = True
            if length < 3:
                print("No fc data for '{}'".format(name)) # should log XXX
                continue
            fc = int(row[2])
            if length < 4:
                print("No cc data for '{}'".format(name)) # should log XXX
                continue
            cc = int(row[3])
            if length < 5:
                print("No dec data for '{}'".format(name)) # should log XXX
                continue
            dec = int(row[3])

            if fc == 0 or fc == 0xFF or cc == 0 or cc == 0xFFFF:
                # this may be a bug in the future, but 00,0000 or FF,FFFF
                # will probably be a data input error
                print("We don't believe in edge cases",
                    "all zeros or all ones on fc/cc for '{}'".format(name))
                continue
            #print((name,is_active,fc,cc,dec))
            new_acl.add(GHCard(fc,cc,name=name,allowed=is_active))

        return new_acl

def main():
    sheets = get_sheets_acl()
    print(sheets)

if __name__ == '__main__':
    main()
